// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":return img`
....ffffff..............
..ffeeeef2f.............
.ffeeeef222f............
.feeeffeeeef............
.ffffee2222ef...........
.fe222ffffe2f...........
fffffffeeefff...........
ffe44ebf44eef...........
fee4d41fddef............
.feee4ddddf.............
..fdde444ef.............
..fdde22ccc.............
...eef22cdc.............
...f4444cddc............
....fffffcddc...........
.....fff..cddc..........
...........cdc..........
............cc..........
........................
........................
........................
........................
........................
........................
`;
            case "image2":return img`
..............ffffff....
.............f2feeeeff..
............f222feeeeff.
............feeeeffeeef.
...........fe2222eeffff.
...........f2effff222ef.
...........fffeeefffffff
...........fee44fbe44eff
............feddf14d4eef
.............fdddd4eeef.
.............fe444eddf..
.............ccc22eddf..
.............cdc22fee...
............cddc4444f...
...........cddcfffff....
..........cddc..fff.....
..........cdc...........
..........cc............
........................
........................
........................
........................
........................
........................
`;
            case "image3":return img`
....ffffff..............
..ffeeeef2f.............
.ffeeeef222f............
.feeeffeeeef............
.ffffee2222ef...........
.fe222ffffe2f...........
fffffffeeefff...........
ffe44ebf44eef...........
fee4d41fddef............
.feee4ddddf.............
..fdde444ef.............
..fdde22ccc.............
...eef22cdc.............
...f4444cddc............
....fffffcddc...........
.....fff..cddc..........
...........cdc..........
............cc..........
........................
........................
........................
........................
........................
........................
`;
            case "image4":return img`
...........fffffff...ccfff..........
..........fbbbbbbbffcbbbbf..........
..........fbb111bbbbbffbf...........
..........fb11111ffbbbbff...........
..........f1cccc1ffbbbbbcff.........
..........ffc1c1c1bbcbcbcccf........
...........fcc3331bbbcbcbcccf..ccccc
............c333c1bbbcbcbccccfcddbbc
............c333c1bbbbbbbcccccddbcc.
............c333c11bbbbbccccccbbcc..
...........cc331c11bbbbccccccfbccf..
...........cc13c11cbbbcccccbbcfccf..
...........c111111cbbbfdddddc.fbbcf.
............cc1111fbdbbfdddc...fbbf.
..............cccfffbdbbfcc.....fbbf
....................fffff........fff
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
